UHF-8478: Remove deprecated helfi_rekry_job_search module
City-of-Helsinki/drupal-helfi-rekry pull request #342
Opened 2023-11-10 12:59 UTC by xkhaven

# [UHF-8478](https://helsinkisolutionoffice.atlassian.net/browse/UHF-8478)

## What was done

* Removed deprecated `field_copied` field from node type `job_listing`
* Removed deprecated module `helfi_rekry_job_search`

## How to install

* Make sure your instance is up and running on correct branch.
  * `git checkout UHF-8478_Remove_field_copied`
  * `make fresh`
* Run `make drush-cr`

## How to test

* [ ] Node type `job_listing` doesn't have field `field_copied`
* [ ] Module `helfi_rekry_job_search` is removed
* [ ] Check that code follows our standards

## Designers review

* [X] This PR does not need designers review

## Other PRs

* https://github.com/City-of-Helsinki/drupal-hdbt/pull/824

2023-11-14 09:01 UTC, Jussiles requested changes
Looks good, but I added couple of comments that should be changed. Also functions from module file should be moved under `helfi_rekry_content.module`

2023-11-14 13:06 UTC, xkhaven commented on conf/cmi/search_api.index.job_listings.yml
> +  custom_value: {  }
Removed this line

2023-11-14 13:06 UTC, xkhaven commented on conf/cmi/helfi_rekry_content.job_listings.yml
> +redirect_403_page: '4848'
Reverted this config

2023-11-14 13:06 UTC, xkhaven commented on public/modules/custom/helfi_rekry_job_search/helfi_rekry_job_search.module
> -function helfi_rekry_job_search_page_attachments_alter(array &$attachments) {
These codes are now copied to `helfi_rekry_content.module`

2023-11-16 11:37 UTC, Jussiles approved these changes
Looks good now! 🦜

2023-11-16 12:42 UTC, merged