UHF-8706
City-of-Helsinki/drupal-helfi-rekry pull request #552
Opened 2024-09-05 11:55 UTC by rpnykanen

# [UHF-8706](https://helsinkisolutionoffice.atlassian.net/browse/UHF-8706)

- Send indexing request to google when a job listing is published.
- A temporary redirect is created for the job listing before sending the request
- Sending deindexing request to google when a job listing is unpublished
- The temporary redirect is removed after the request.

## What was done
- Google api integration using google's integration library
- Read the documentation

## How to install

* Make sure your instance is up and running on correct branch.
  * `git checkout UHF-8706`
  * `make fresh`
* Run `make drush-cr`

- If you want to try out actual requests, get the api key and add it to local.settings
 `$config['helfi_google_api.settings']['indexing_api_key'] = 'key-goes-here'`

## How to test

- Select one of the job listings which is not published
- Schedule it to be published within a minute or two
- Manually run `drush cron` after the scheduled time
- Go read logs and you should see something

Repeat the previous, but with unpublish scheduling

You can try sending a status request by running drush-command. This one has been tested through the api.
`drush helfi:google-entity-index-status https://hel.fi/fi/avoimet-tyopaikat/avoimet-tyopaikat/sotepe-02-353-24`

## Continuous documentation

* [ ] This feature has been documented/the documentation has been updated
* [ ] This change doesn't require updates to the documentation

2024-09-06 08:54 UTC, tuutti requested changes

2024-09-10 08:47 UTC, khalima approved these changes
Works on local environment until the request is sent to Google API, but this is a known issue because there's no testing API.

2024-09-10 11:55 UTC, tuutti requested changes

2024-09-11 08:39 UTC, tuutti requested changes

2024-09-11 08:39 UTC, tuutti commented on public/modules/custom/helfi_google_api/src/JobIndexingService.php
> +  private function handleDebugMessage(Response $response) {
Missing return type

2024-09-11 08:53 UTC, merged